### ISSUE TITLE
[ETH] Stepper Pure Component

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1292]
Implement the pure version of the stepper component.

Create a stepper, as a Pure React component: 
- (1) Sending ETH…
- (2) Order is Created…
- (3) Receive { tokenSymbol }

![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/66bc3720-7b45-4354-971a-fce623e5517e)

For more detail, see the Figma: https://www.figma.com/proto/sUwumNFlcslHzShSZJHVsS/2022_COW-Native-ETH-Flow?page-id=1201%3A382&node-id=1204%3A674&viewport=-96%2C1616%2C0.19&scaling=min-zoom&starting-point-node-id=1204%3A674

## Tasks
- [x] Create Pure Component
- [x] Define simple Model
- [x] Create Cosmos
- [x] Handle basic markup: Map state to HTML
- [x] Design / Nice CSS HTML @fairlighteth

**Comment by alfetopito** [comment]
Partially addressed on https://github.com/cowprotocol/cowswap/pull/1402
Missing design by Michel

**Comment by anxolin** [comment]
Updated the tasks and assigned to @fairlighteth
