### ISSUE TITLE
[ETH] Cancelations: Handle State Changes

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1299]
Make sure the order status is updated correctly

## Tasks
- [x] Handle the states:
   - CANCELATION_INITIATED
   - CANCELATION_COMPLETED
- [x] Make sure the link to Etherscan work
- [x] Handle the state changes

## Context
- [Hard Cancelations](https://docs.google.com/document/d/1PvLHosAj2ZTkIFfBLRv_St-IsVtOgpwYDWnFhAJyE7Q/edit#heading=h.mazpu036s3yf)
-  [Figma Wireframes](https://www.figma.com/proto/sUwumNFlcslHzShSZJHVsS/2022_COW-Native-ETH-Flow?page-id=1201%3A382&node-id=1210%3A1334&viewport=-96%2C1616%2C0.19&scaling=min-zoom&starting-point-node-id=1204%3A674)
