### ISSUE TITLE
[ETH] Final tests / QA approvals

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1303]
# Tasks
- [ ] Create Release candidate
- [ ] QA Tests in staging / barn
- [ ] Deploy to production
- [ ] Announcements!
