### ISSUE TITLE
[LIMIT] [6-Enable] Enable Limit Orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1345]
Allow users to voluntarilly enable Limit Orders

According to Mindy’s studies, most of the users will fill Limit Orders functionality is incomplete unless we really have partial fills. Additionally, there's some concerns about the fee and the execution price (on how clear it is for users). For this reason, this will be at first an experimental feature.

Partial fills and better fee communication will take longer, so it makes sense to release early (some users might appreciate to have at least the fill or kill option. However, it becomes important to handle expectations and clearly show Limit Orders as work in progress, with only fill or kill for the time being. 

![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/1a8d4dfd-be61-46a7-834d-77e974e01b37)

# Tasks

- [ ] Persist / Load setting flag for enabling Limit Orders
- [ ] Show Beta content if disabled
- [ ] Show Limit orders if enabled
