### ISSUE TITLE
[LIMIT] [8-History] Load Open Orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1352]
Load and display open orders in the table. 

It will sort the orders by creation time (newest orders first)

# Tasks
- [ ] Create container component and delegate in the pure one
- [ ] Load Orders from API. It will load both:
     - Limit Orders
     - Market Orders (swaps)
- [ ] Handling Loading state: Show a shimmering effect while loading
- [ ] It will sort the orders by creation time (newest orders first)
- [ ] Make sure that newly created orders will immediately show up in the Open orders.
