### ISSUE TITLE
[LIMIT] Deploy to Barn

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1374]
Deploy to Barn (test with cow stars)

# Tasks
- [ ] Create basic Release candidate
- [ ] QA Tests
- [ ] Deploy to barn
- [ ] Announce in Discord, and engage with CoW ⭐️s
