### ISSUE TITLE
[LIMIT] Final test / QA Approvals

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1375]
Test and deploy to production

# Tasks
- [ ] Create Release candidate
- [ ] QA Tests in barn/staging
- [ ] Deploy to production
- [ ] Announcements!
