### ISSUE TITLE
Technical debt

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#212]
**Description**

Epic to track technical debt

> This issue is always Open, and in our "Nexts Sprints". In each sprint, we will select some improvements and execute.

**Performance related**
- [x] 🔥 Size of bundle https://cowswap.exchange/static/js/4.a5add725.chunk.js.map is 14MB. Review what is there
- [x] Re-enable Service Workers
- [x] Take a look at proper library tree shaking, big libraries, or big JSONS of unused ABIs
- [x] Build time speedup: Bottle necks, unused things that we can ignore in typescript, or webpack
- [x] Token list
  - [ ] Enable Coingecko
  - [ ] Optimize list loading performance, token selection is slow!
- [x] FAQ is super slow (too big) --> React Window? other solutions?
- [x] Optimize token balance balance checks
- [x] Check if/why price fetching is slow/makes the app slow
- [x] Check whether SWR would be a good fit for optmizing data fetching/caching/retries: https://swr.vercel.app/docs/getting-started
- [x] Unnecesary calls to the API (i.e. USD price estimation)
- Improve logic of PRICE/FEE, its inneficient and queries several times the same enpoint: See  https://gnosisinc.slack.com/archives/CSGLUC1BN/p1637761787180400 and https://gnosisinc.slack.com/archives/CSGLUC1BN/p1637691278174700
- [ ] Infura keys are missing for the new COW Organization

**Error handling**
- [x] console.logs! During app start up, during app execution
- [x] Sentry: Go over unhandled errors

**Tracking**
- [x] Analytics for affiliate
  - [x] Track copy button?
  - [x] Links followed - probably already on google analytics

**Misc**
- [x] Barn for explorer (https://github.com/gnosis/gp-ui/pull/850 and https://github.com/gnosis/cowswap/pull/1890)
- [x] Update banner on `barn.cowswap.exchange` to match the domain (https://github.com/gnosis/cowswap/pull/1889)
- [x] Update GP-UI TS version to latest https://github.com/gnosis/gp-ui/pull/904
- [x] Issues in github are growing. Find ways to either archive or tag them so they are low prio (so we remove them from sight)

> Original issue https://github.com/gnosis/cowswap/issues/1887 by @alfetopito
