### ISSUE TITLE
Welcome screen and improve context

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#222]
As a first time user, i would like to understand when i first use CowSwap why should I use it and what a re the key differences

We could evaluate this with the newbie hat, the tech savvy one, the basic crypto retail one, and the defi degen one

- [ ] Welcome screen (TBD)
- [ ] Improve FAQ
- [ ] Improve messages
- [ ] Revisit main workflow
- [ ] Revisit edge cases

> Original issue https://github.com/gnosis/cowswap/issues/1944 by @anxolin
