### ISSUE TITLE
Frame wallet

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#267]
**Description**

Verify we are compatible with Frame wallet https://frame.sh/

**Additional context**

I believe we already are compatible, but we should try to make sure there are no caveats and it works.

**Related issues**

- [ ] https://github.com/gnosis/cowswap/issues/1983
- [ ] https://github.com/gnosis/cowswap/issues/1974
- [ ] https://github.com/gnosis/cowswap/issues/1972
- [ ] https://github.com/gnosis/cowswap/issues/1971
- [ ] https://github.com/gnosis/cowswap/issues/1970

> Original issue https://github.com/gnosis/cowswap/issues/2367 by @alfetopito

**Comment by elena-zh** [comment]
Closing for now. Can be re-opened when appears in the roadmap :)
