### ISSUE TITLE
Epic: Replace orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#304]
**Description**

Allow users to replace existing orders

**Additional resources**

This feature involves allowing users to, in a single operation, cancel existing orders and replace it with a new one.

It also allows users to "replay" existing orders by pre-filing the UI with data for a previous order.

**Feature breakdown**
It includes:
- [ ] Adding to recent activity [1]
- [ ] Recreate order (Canceled / Filled) UI [5]
- [ ] Replace order (Pending) [10]
- [ ] Sign the order: Add meta-info to the order so backend ensures that only one of the orders are executed [2]
- [ ] Replacing/Replace logic for old pending: only for new [5]

Good to have:
- [ ] ???

> Original issue https://github.com/gnosis/cowswap/issues/2467 by @alfetopito

**Comment by alfetopito** [comment]
Are we giving up on this feature?
