### ISSUE TITLE
Tokens refactoring

### ISSUE THREAD

**Issue by shoom3301** [cowprotocol/cowswap#3195]
**Description**

**Performance**

Before:

<img width="1728" alt="Screenshot 2023-10-10 at 13 52 18" src="https://github.com/cowprotocol/cowswap/assets/7122625/233ad6db-9d6c-468e-a966-ee535ce1b0c9">

After:
<img width="1727" alt="Screenshot 2023-10-10 at 13 52 10" src="https://github.com/cowprotocol/cowswap/assets/7122625/a8b3bdc7-773e-45ea-b6a5-a996ec1d91c9">

**Feature breakdown**
It includes:
- [ ] New library for tokens
- [ ] Refactor Uniswap token entities usage (Currency -> TokenWithLogo)
- [ ] New UI for tokens search and management
- [ ] Integrate new lib+ui into App
- [ ] Remove legacy code
