### ISSUE TITLE
Gnosis Safe App Improvements

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#420]
This epics tries to aggregate a group of nice features, fixes and improvements for CowSwap and Gnosis Safe integrations.

The main improvements are:
* [ ] **SafeApp**: Make sure CowSwap works as a Gnosis Safe App
* [ ] **Bundling of transactions**: #319
* [ ] **Decode AppId**: Make sure Gnosis Safe decode the AppId and display the trade details to the user before they sign
* [ ] See this thread for more improvements https://cowservices.slack.com/archives/C0369KJB143/p1654765065424699 
* [ ] UX Research on user pain points

Other than the features above, there's a bunch of issues/improvements that would be great to add:
* See the items in the epic
