### ISSUE TITLE
[promotion] Create an affiliate program

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#4238]
Add a affiliate program, so people can share with their audiences a link that.

The URL would have some field. Potentially a receiver account, or maybe a code a receiver account. Some discussion about the potential programs need to happen.

Ideally, the backend would be able to give some advantage to the user following the link, for example:
- Fee discount, or even Free with some conditions (with fee, I'm referring to the gas cost)
- Partner fee discount. It could be a good idea to add either the affiliate program 

## Potential ideas on how this could be used
(add yours, just brainstorming)
- Add a fee (gas cost) discount to the person following link, and some cow based on volume to the promoter
- Allow to buy locked COW at a discount (i.e Market price -5% with 1 year locking period). Promoters get also locked COW
- Implement happy hours to encourage Coincidence of Wants

## Context
https://cowservices.slack.com/archives/C036G0J90BU/p1712848795412039

## Task
- [ ] Think on potential affiliate plans
- [ ] Coordintate with backend, in case there's some dependencies
- [ ] Decide the format for appData metadata involved
- [ ] Implementation
- [ ] Widget implementation
