### ISSUE TITLE
[Account] Main page

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#571]
### TODO
- [x] Cow balance
- [x] Tiers
- [x] Split what is currently on profile page into separate pages (start at account-page branch)

### Good to have
- [ ] [good to have] High overview of your account (i.e.should we show surplus, trades, etc.)
- [ ] Open orders
- [ ] History (should we have filters?)
